[tool.poetry]
name = "posted"
version = "0.1.0"
description = "Potsdam open-source techno-economic database"
authors = ["Philipp Verpoort <philipp.verpoort@pik-potsdam.de>"]

[tool.poetry.dependencies]
python = "~3.10.10"
pybtex = "^0.24.0"
pybtex-apa-style = "^1.3"
numpy = "^1.24.2"
pandas = "^1.5.3"
pyyaml = "^6.0"
pint = "^0.20.1"
pyside6 = "^6.5.0"
sigfig = "^1.3.2"
pint-pandas = "^0.3"

[tool.poetry.dev-dependencies]
pyside6 = "^6.5.0"
pyinstaller = "^5.11.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
