[tool.poetry]
name = "posted"
version = "0.1.0"
description = "Potsdam open-source techno-economic database"
authors = ["Philipp Verpoort <philipp.verpoort@pik-potsdam.de>"]

[tool.poetry.dependencies]
python = "^3.8"
pybtex = "^0.24.0"
pybtex-apa-style = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
