name: test_automation

on:
  push:
    branches:
      - develop  # or the branch you want to trigger the workflow on pull requests

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.12]  # Versions of Python to test against

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install  # Ensure all dependencies are installed

    - name: Run tests
      if: always()
      run: |
         poetry run python - m unittest discover
        
    - name: Lint python code with flake8
      if: always()
      run: |
        poetry run flake8 .
        

        
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::lintr, local::.
        needs: lint

    - name: Lint
      run: lintr::lint_package()
      shell: Rscript {0}
      env:
        LINTR_ERROR_ON_LINT: true
