name: Deploy Documentation

on:
  push:
    branches:
      - develop # You can specify any branch you want to trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Install R dependencies
        run: |
          R -e "install.packages('renv')"
          R -e "renv::restore()"

      - name: Run Makefile
        run: make

      - name: Install mkdocs and mike
        run: |
          python -m pip install mkdocs
          python -m pip install mike

      - name: Deploy documentation to GitHub Pages
        run: |
          mike deploy --push --update-aliases

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Push changes to gh-pages
        run: |
          git add .
          git commit -m "Update documentation"
          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
