variable:
  name: Variable
  desc: Name of the variable contributed by this row.
  dtype: category
  required: True
  allowed: Any variable in accordance with the variable definitions.
region:
  name: Region
  desc: The region that this value is reported for, if any.
  dtype: str
  required: False
  allowed: Any country or region specification.
period:
  name: Period
  desc:
    The period that this value is reported for. Leaving this field empty means that the date of publication should 
    be assumed instead.
  dtype: float
  required: False
  allowed: Any integer number referring to a year (e.g. 1995, 2023, 2040, ...)
component:
  name: Component
  desc: The name of the component if multiple components of this entry type exist.
  dtype: str
  required: False
  allowed:
    This is a free text field explaining the component. It should be left empty if only one component exists.
reported_value:
  name: Reported value
  desc: The exact number reported by the referenced source, expressed in the original units.
  dtype: float
  required: True
  allowed: Any floating-point number
reported_unc:
  name: Reported uncertainty
  desc: The uncertainty on the reported value by the referenced source if reported.
  dtype: float
  required: False
  allowed: Any floating-point number
reported_unit:
  name: Reported unit
  desc: The unit that the value and uncertainty were reported in.
  dtype: str
  required: True
  allowed: Any unit matching the entry type
reference_value:
  name: Reference value
  desc:
    The value that the reported value is referring to (the capacity or operation). If kept empty, a default 
    reference value of 1.0 is assumed.
  dtype: float
  required: False
  allowed: Any floating-point number
reference_unit:
  name: Reference unit
  desc:
    The unit that the reported unit is referring to (the capacity or operation). If kept empty, a the default 
    reference value for that technology is used.
  dtype: str
  required: False
  allowed: Any unit compatible with the entry type for the respective technology.
comment:
  name: Comment
  desc: A free text field commenting on this entry.
  dtype: str
  required: False
  allowed: Any text.
source:
  name: Source reference
  desc: A reference to the source it was taken from.
  dtype: str
  required: False
  allowed: Exactly one reference identifier.
source_detail:
  name: Source detail
  desc: Details on where in the source the data correpsonding to the entry can be found.
  dtype: str
  required: False
  allowed: Any text.
